### ISSUE TITLE
TypeError: Cannot read property 'publicClusters' of undefined

### ISSUE THREAD

**Issue by atomicquasar** [howtographql/graphql-js#11]
Good afternoon,

I have cloned the repository, and have installed and run dependancies as instructed, however I am getting the following error. Do you know what may be causing this?

TypeError: Cannot read property 'publicClusters' of undefined
    at Environment.<anonymous> (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphcool-yml/dist/Environment.js:103:39)
    at step (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphcool-yml/dist/Environment.js:40:23)
    at Object.next (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphcool-yml/dist/Environment.js:21:53)
    at fulfilled (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphcool-yml/dist/Environment.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:38543) UnhandledPromiseRejectionWarning: Error: No cluster set. Please set the "cluster" property in your graphcool.yml
    at /Users/Charles/Sites/tutorials/graphql-js/node_modules/graphql-config-extension-graphcool/dist/index.js:137:31
    at step (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphql-config-extension-graphcool/dist/index.js:40:23)
    at Object.next (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphql-config-extension-graphcool/dist/index.js:21:53)
    at fulfilled (/Users/Charles/Sites/tutorials/graphql-js/node_modules/graphql-config-extension-graphcool/dist/index.js:12:58)
    at <anonymous>
(node:38543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by marktani** [comment]
Hey @atomicquasar, can you share the exact steps that you take to reproduce this issue? 🙂

**Comment by a-eid** [comment]
I'm having the same issue, 

@marktani 

#### steps to reproduce

- clone repo
- `yarn && yarn start` 
- visit `localhost:4000`

**Comment by marktani** [comment]
Thanks @atomicquasar and @a-eid, I upgraded `graphql-yoga` to fix this problem.

Please follow [the tutorial](https://www.howtographql.com/graphql-js/1-getting-started/) to setup the requirements correctly before cloning this repository.

**Comment by a-eid** [comment]
Thanks. @marktani 

I just cloned the repo and upon visiting `localhost:4000` 
I get the following error.

```
Server is running on http://localhost:4000                                                                           
(node:28719) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cluster local provided in graphcool.yml could not be found in global ~/.graphcoolrc.                                                     
Please check in ~/.graphcoolrc under 'graphcool-1.0', if the cluster exists.                                           
You can use `graphcool local start` to start a new cluster.                       
(node:28719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
