### ISSUE TITLE
I have problem with es6 syntax

### ISSUE THREAD

**Issue by vinhtq** [howtographql/graphql-js#18]
When i try to run ```yarn dev``` I always have this issue

```
graphql-js/src/index.js:19
    ...req,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

Im running node v6.11.3

I think this might be relate to es6 syntax for rest operator

**Comment by marktani** [comment]
Upgrade your node version to 8+ and it should work 🙂

**Comment by vinhtq** [comment]
Yes it works. Thank you so much!

**Comment by marktani** [comment]
Cheers!
