### ISSUE TITLE
When I use string file path for typeDefs,there is a error: Cannot parse the unexpected character "/". 

### ISSUE THREAD

**Issue by rumsky** [howtographql/graphql-js#29]
When I use string file path for typeDefs,there is a error: Cannot parse the unexpected character "/". 
```
const server = new GraphQLServer({
    typeDefs: './src/schema.graphql',
    resolvers,
})
```

/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/lexer.js:302
  throw (0, _error.syntaxError)(source, pos, unexpectedCharacterMessage(code));
  ^
GraphQLError: Syntax Error: Cannot parse the unexpected character "/".
    at syntaxError (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/error/syntaxError.js:24:10)
    at readToken (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/lexer.js:302:32)
    at Object.lookahead (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/lexer.js:61:43)
    at Object.advanceLexer [as advance] (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/lexer.js:52:33)
    at expect (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/parser.js:1296:11)
    at parseDocument (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/parser.js:107:3)
    at Object.parse (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql/language/parser.js:38:10)
    at getDocumentFromSDL (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql-import/dist/index.js:107:26)
    at Object.importSchema (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql-import/dist/index.js:59:20)
    at mergeTypeDefs (/Users/harry/reactworkspace/graphql-yoga-server/hackernews-node/node_modules/graphql-yoga/dist/index.js:402:37)

**Comment by itscarlosrufo** [comment]
Thanks @rumsky for opening this issue 😄. It seems to be solved following the latest docs. Closing this for now, please, feel free to open an issue if you cannot make it work!
