### ISSUE TITLE
Authentication: Cannot find 'bcryptjs'

### ISSUE THREAD

**Issue by abykal** [howtographql/graphql-js#43]
ERROR:Cannot find module bcryptjs. 
I got this error while doing node src/index.js at end of the Authentication section.
```
module.js:549
    throw err;
    ^
Error: Cannot find module 'bcryptjs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/aby/Developer/Projects/React/GraphQL/hackernews-node/src/resolvers/Mutation.js:1:78)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I deleted node_modules folder and reinstalled all via `npm install`. Still bcryptjs is missing.
My package.json shows  
```
"dependencies": {
    "bcrypt": "^3.0.0",
    "graphql-yoga": "^1.16.2",
    "jsonwebtoken": "^8.3.0",
    "prisma-binding": "^2.1.5"
  }
```

**Comment by Elfayer** [comment]
These are two different packages.
You're using: https://www.npmjs.com/package/bcrypt
They are using: https://www.npmjs.com/package/bcryptjs
Look at the [package.json](https://github.com/howtographql/graphql-js/blob/master/package.json)

**Comment by abykal** [comment]
Thanks @Elfayer.

**Comment by cypriantingiweh** [comment]
run this command in the project npm install bcryptjs

**Comment by mrlopezharo** [comment]
domo arigatou gozaimasu
